version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception
    expose:
      - "3306"
    env_file: .env
    restart: always
  
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
      - adminer
    build: 
      context: requirements/nginx/
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    ports:
      - "443:443"
    env_file: .env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress/
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    restart: always
    expose:
      - "9000"
    env_file: .env

  redis:
    container_name: redis
    image: redis
    build: requirements/bonus/redis/
    depends_on:
      - wordpress
    networks:
      - inception
    expose:
      - "6379"
    restart: always
  
  adminer:
    container_name: adminer
    image: adminer
    build: requirements/bonus/adminer/
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/maaliber/data/wordpress'
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/maaliber/data/mariadb'

networks:
  inception:
    driver: bridge